import { A } from '@ember/array';


export const CURRENCIES_LIST = A([
  {iso3: 'AED', isoNumeric: '784', symbol: ''    , name: 'United Arab Emirates dirham'                               },
  {iso3: 'AFN', isoNumeric: '971', symbol: '؋'   , name: 'Afghan afghani'                                            },
  {iso3: 'ALL', isoNumeric: '8'  , symbol: 'Lek' , name: 'Albanian lek'                                              },
  {iso3: 'AMD', isoNumeric: '51' , symbol: ''    , name: 'Armenian dram'                                             },
  {iso3: 'ANG', isoNumeric: '532', symbol: 'ƒ'   , name: 'Netherlands Antillean guilder'                             },
  {iso3: 'AOA', isoNumeric: '973', symbol: ''    , name: 'Angolan kwanza'                                            },
  {iso3: 'ARS', isoNumeric: '32' , symbol: '$'   , name: 'Argentine peso'                                            },
  {iso3: 'AUD', isoNumeric: '36' , symbol: '$'   , name: 'Australian dollar'                                         },
  {iso3: 'AWG', isoNumeric: '533', symbol: 'ƒ'   , name: 'Aruban florin'                                             },
  {iso3: 'AZN', isoNumeric: '944', symbol: 'ман' , name: 'Azerbaijani manat'                                         },
  {iso3: 'BAM', isoNumeric: '977', symbol: 'KM'  , name: 'Bosnia and Herzegovina convertible mark'                   },
  {iso3: 'BBD', isoNumeric: '52' , symbol: '$'   , name: 'Barbados dollar'                                           },
  {iso3: 'BDT', isoNumeric: '50' , symbol: ''    , name: 'Bangladeshi taka'                                          },
  {iso3: 'BGN', isoNumeric: '975', symbol: 'лв'  , name: 'Bulgarian lev'                                             },
  {iso3: 'BHD', isoNumeric: '48' , symbol: ''    , name: 'Bahraini dinar'                                            },
  {iso3: 'BIF', isoNumeric: '108', symbol: ''    , name: 'Burundian franc'                                           },
  {iso3: 'BMD', isoNumeric: '60' , symbol: '$'   , name: 'Bermudian dollar'                                          },
  {iso3: 'BND', isoNumeric: '96' , symbol: '$'   , name: 'Brunei dollar'                                             },
  {iso3: 'BOB', isoNumeric: '68' , symbol: '$b'  , name: 'Boliviano'                                                 },
  {iso3: 'BOV', isoNumeric: '984', symbol: ''    , name: 'Bolivian Mvdol (funds code)'                               },
  {iso3: 'BRL', isoNumeric: '986', symbol: 'R$'  , name: 'Brazilian real'                                            },
  {iso3: 'BSD', isoNumeric: '44' , symbol: '$'   , name: 'Bahamian dollar'                                           },
  {iso3: 'BTN', isoNumeric: '64' , symbol: ''    , name: 'Bhutanese ngultrum'                                        },
  {iso3: 'BWP', isoNumeric: '72' , symbol: 'P'   , name: 'Botswana pula'                                             },
  {iso3: 'BYN', isoNumeric: '933', symbol: 'Br'  , name: 'Belarusian ruble'                                          },
  {iso3: 'BZD', isoNumeric: '84' , symbol: 'BZ$' , name: 'Belize dollar'                                             },
  {iso3: 'CAD', isoNumeric: '124', symbol: '$'   , name: 'Canadian dollar'                                           },
  {iso3: 'CDF', isoNumeric: '976', symbol: ''    , name: 'Congolese franc'                                           },
  {iso3: 'CHE', isoNumeric: '947', symbol: ''    , name: 'WIR Euro (complementary currency)'                         },
  {iso3: 'CHF', isoNumeric: '756', symbol: 'CHF' , name: 'Swiss franc'                                               },
  {iso3: 'CHW', isoNumeric: '948', symbol: ''    , name: 'WIR Franc (complementary currency)'                        },
  {iso3: 'CLF', isoNumeric: '990', symbol: ''    , name: 'Unidad de Fomento (funds code)'                            },
  {iso3: 'CLP', isoNumeric: '152', symbol: '$'   , name: 'Chilean peso'                                              },
  {iso3: 'CNY', isoNumeric: '156', symbol: '¥'   , name: 'Chinese yuan'                                              },
  {iso3: 'COP', isoNumeric: '170', symbol: '$'   , name: 'Colombian peso'                                            },
  {iso3: 'COU', isoNumeric: '970', symbol: ''    , name: 'Unidad de Valor Real (UVR) (funds code)'                   },
  {iso3: 'CRC', isoNumeric: '188', symbol: '₡'   , name: 'Costa Rican colon'                                         },
  {iso3: 'CUC', isoNumeric: '931', symbol: ''    , name: 'Cuban convertible peso'                                    },
  {iso3: 'CUP', isoNumeric: '192', symbol: '₱'   , name: 'Cuban peso'                                                },
  {iso3: 'CVE', isoNumeric: '132', symbol: ''    , name: 'Cape Verde escudo'                                         },
  {iso3: 'CZK', isoNumeric: '203', symbol: 'Kč'  , name: 'Czech koruna'                                              },
  {iso3: 'DJF', isoNumeric: '262', symbol: ''    , name: 'Djiboutian franc'                                          },
  {iso3: 'DKK', isoNumeric: '208', symbol: 'kr'  , name: 'Danish krone'                                              },
  {iso3: 'DOP', isoNumeric: '214', symbol: 'RD$' , name: 'Dominican peso'                                            },
  {iso3: 'DZD', isoNumeric: '12' , symbol: ''    , name: 'Algerian dinar'                                            },
  {iso3: 'EGP', isoNumeric: '818', symbol: '£'   , name: 'Egyptian pound'                                            },
  {iso3: 'ERN', isoNumeric: '232', symbol: ''    , name: 'Eritrean nakfa'                                            },
  {iso3: 'ETB', isoNumeric: '230', symbol: ''    , name: 'Ethiopian birr'                                            },
  {iso3: 'EUR', isoNumeric: '978', symbol: '€'   , name: 'Euro'                                                      },
  {iso3: 'FJD', isoNumeric: '242', symbol: '$'   , name: 'Fiji dollar'                                               },
  {iso3: 'FKP', isoNumeric: '238', symbol: '£'   , name: 'Falkland Islands pound'                                    },
  {iso3: 'GBP', isoNumeric: '826', symbol: '£'   , name: 'Pound sterling'                                            },
  {iso3: 'GEL', isoNumeric: '981', symbol: ''    , name: 'Georgian lari'                                             },
  {iso3: 'GHS', isoNumeric: '936', symbol: '¢'   , name: 'Ghanaian cedi'                                             },
  {iso3: 'GIP', isoNumeric: '292', symbol: '£'   , name: 'Gibraltar pound'                                           },
  {iso3: 'GMD', isoNumeric: '270', symbol: ''    , name: 'Gambian dalasi'                                            },
  {iso3: 'GNF', isoNumeric: '324', symbol: ''    , name: 'Guinean franc'                                             },
  {iso3: 'GTQ', isoNumeric: '320', symbol: 'Q'   , name: 'Guatemalan quetzal'                                        },
  {iso3: 'GYD', isoNumeric: '328', symbol: '$'   , name: 'Guyanese dollar'                                           },
  {iso3: 'HKD', isoNumeric: '344', symbol: '$'   , name: 'Hong Kong dollar'                                          },
  {iso3: 'HNL', isoNumeric: '340', symbol: 'L'   , name: 'Honduran lempira'                                          },
  {iso3: 'HRK', isoNumeric: '191', symbol: 'kn'  , name: 'Croatian kuna'                                             },
  {iso3: 'HTG', isoNumeric: '332', symbol: ''    , name: 'Haitian gourde'                                            },
  {iso3: 'HUF', isoNumeric: '348', symbol: 'Ft'  , name: 'Hungarian forint'                                          },
  {iso3: 'IDR', isoNumeric: '360', symbol: 'Rp'  , name: 'Indonesian rupiah'                                         },
  {iso3: 'ILS', isoNumeric: '376', symbol: '₪'   , name: 'Israeli new shekel'                                        },
  {iso3: 'INR', isoNumeric: '356', symbol: ''    , name: 'Indian rupee'                                              },
  {iso3: 'IQD', isoNumeric: '368', symbol: ''    , name: 'Iraqi dinar'                                               },
  {iso3: 'IRR', isoNumeric: '364', symbol: '﷼'   , name: 'Iranian rial'                                              },
  {iso3: 'ISK', isoNumeric: '352', symbol: 'kr'  , name: 'Icelandic króna'                                           },
  {iso3: 'JMD', isoNumeric: '388', symbol: 'J$'  , name: 'Jamaican dollar'                                           },
  {iso3: 'JOD', isoNumeric: '400', symbol: ''    , name: 'Jordanian dinar'                                           },
  {iso3: 'JPY', isoNumeric: '392', symbol: '¥'   , name: 'Japanese yen'                                              },
  {iso3: 'KES', isoNumeric: '404', symbol: ''    , name: 'Kenyan shilling'                                           },
  {iso3: 'KGS', isoNumeric: '417', symbol: 'лв'  , name: 'Kyrgyzstani som'                                           },
  {iso3: 'KHR', isoNumeric: '116', symbol: '៛'   , name: 'Cambodian riel'                                            },
  {iso3: 'KMF', isoNumeric: '174', symbol: ''    , name: 'Comoro franc'                                              },
  {iso3: 'KPW', isoNumeric: '408', symbol: '₩'   , name: 'North Korean won'                                          },
  {iso3: 'KRW', isoNumeric: '410', symbol: '₩'   , name: 'South Korean won'                                          },
  {iso3: 'KWD', isoNumeric: '414', symbol: ''    , name: 'Kuwaiti dinar'                                             },
  {iso3: 'KYD', isoNumeric: '136', symbol: '$'   , name: 'Cayman Islands dollar'                                     },
  {iso3: 'KZT', isoNumeric: '398', symbol: 'лв'  , name: 'Kazakhstani tenge'                                         },
  {iso3: 'LAK', isoNumeric: '418', symbol: '₭'   , name: 'Lao kip'                                                   },
  {iso3: 'LBP', isoNumeric: '422', symbol: '£'   , name: 'Lebanese pound'                                            },
  {iso3: 'LKR', isoNumeric: '144', symbol: '₨'   , name: 'Sri Lankan rupee'                                          },
  {iso3: 'LRD', isoNumeric: '430', symbol: '$'   , name: 'Liberian dollar'                                           },
  {iso3: 'LSL', isoNumeric: '426', symbol: ''    , name: 'Lesotho loti'                                              },
  {iso3: 'LYD', isoNumeric: '434', symbol: ''    , name: 'Libyan dinar'                                              },
  {iso3: 'MAD', isoNumeric: '504', symbol: ''    , name: 'Moroccan dirham'                                           },
  {iso3: 'MDL', isoNumeric: '498', symbol: ''    , name: 'Moldovan leu'                                              },
  {iso3: 'MGA', isoNumeric: '969', symbol: ''    , name: 'Malagasy ariary'                                           },
  {iso3: 'MKD', isoNumeric: '807', symbol: 'ден' , name: 'Macedonian denar'                                          },
  {iso3: 'MMK', isoNumeric: '104', symbol: ''    , name: 'Myanmar kyat'                                              },
  {iso3: 'MNT', isoNumeric: '496', symbol: '₮'   , name: 'Mongolian tögrög'                                          },
  {iso3: 'MOP', isoNumeric: '446', symbol: ''    , name: 'Macanese pataca'                                           },
  {iso3: 'MRO', isoNumeric: '478', symbol: ''    , name: 'Mauritanian ouguiya'                                       },
  {iso3: 'MUR', isoNumeric: '480', symbol: '₨'   , name: 'Mauritian rupee'                                           },
  {iso3: 'MVR', isoNumeric: '462', symbol: ''    , name: 'Maldivian rufiyaa'                                         },
  {iso3: 'MWK', isoNumeric: '454', symbol: ''    , name: 'Malawian kwacha'                                           },
  {iso3: 'MXN', isoNumeric: '484', symbol: '$'   , name: 'Mexican peso'                                              },
  {iso3: 'MXV', isoNumeric: '979', symbol: ''    , name: 'Mexican Unidad de Inversion(UDI) (funds code)'             },
  {iso3: 'MYR', isoNumeric: '458', symbol: 'RM'  , name: 'Malaysian ringgit'                                         },
  {iso3: 'MZN', isoNumeric: '943', symbol: 'MT'  , name: 'Mozambican metical'                                        },
  {iso3: 'NAD', isoNumeric: '516', symbol: '$'   , name: 'Namibian dollar'                                           },
  {iso3: 'NGN', isoNumeric: '566', symbol: '₦'   , name: 'Nigerian naira'                                            },
  {iso3: 'NIO', isoNumeric: '558', symbol: 'C$'  , name: 'Nicaraguan córdoba'                                        },
  {iso3: 'NOK', isoNumeric: '578', symbol: 'kr'  , name: 'Norwegian krone'                                           },
  {iso3: 'NPR', isoNumeric: '524', symbol: '₨'   , name: 'Nepalese rupee'                                            },
  {iso3: 'NZD', isoNumeric: '554', symbol: '$'   , name: 'New Zealand dollar'                                        },
  {iso3: 'OMR', isoNumeric: '512', symbol: '﷼'   , name: 'Omani rial'                                                },
  {iso3: 'PAB', isoNumeric: '590', symbol: 'B/.' , name: 'Panamanian balboa'                                         },
  {iso3: 'PEN', isoNumeric: '604', symbol: 'S/.' , name: 'Peruvian Sol'                                              },
  {iso3: 'PGK', isoNumeric: '598', symbol: ''    , name: 'Papua New Guinean kina'                                    },
  {iso3: 'PHP', isoNumeric: '608', symbol: '₱'   , name: 'Philippine peso'                                           },
  {iso3: 'PKR', isoNumeric: '586', symbol: '₨'   , name: 'Pakistani rupee'                                           },
  {iso3: 'PLN', isoNumeric: '985', symbol: 'zł'  , name: 'Polish złoty'                                              },
  {iso3: 'PYG', isoNumeric: '600', symbol: 'Gs'  , name: 'Paraguayan guaraní'                                        },
  {iso3: 'QAR', isoNumeric: '634', symbol: '﷼'   , name: 'Qatari riyal'                                              },
  {iso3: 'RON', isoNumeric: '946', symbol: 'lei' , name: 'Romanian leu'                                              },
  {iso3: 'RSD', isoNumeric: '941', symbol: 'Дин.', name: 'Serbian dinar'                                             },
  {iso3: 'RUB', isoNumeric: '643', symbol: '₽'   , name: 'Russian ruble'                                             },
  {iso3: 'RWF', isoNumeric: '646', symbol: ''    , name: 'Rwandan franc'                                             },
  {iso3: 'SAR', isoNumeric: '682', symbol: '﷼'   , name: 'Saudi riyal'                                               },
  {iso3: 'SBD', isoNumeric: '90' , symbol: '$'   , name: 'Solomon Islands dollar'                                    },
  {iso3: 'SCR', isoNumeric: '690', symbol: '₨'   , name: 'Seychelles rupee'                                          },
  {iso3: 'SDG', isoNumeric: '938', symbol: ''    , name: 'Sudanese pound'                                            },
  {iso3: 'SEK', isoNumeric: '752', symbol: 'kr'  , name: 'Swedish krona/kronor'                                      },
  {iso3: 'SGD', isoNumeric: '702', symbol: '$'   , name: 'Singapore dollar'                                          },
  {iso3: 'SHP', isoNumeric: '654', symbol: '£'   , name: 'Saint Helena pound'                                        },
  {iso3: 'SLL', isoNumeric: '694', symbol: ''    , name: 'Sierra Leonean leone'                                      },
  {iso3: 'SOS', isoNumeric: '706', symbol: 'S'   , name: 'Somali shilling'                                           },
  {iso3: 'SRD', isoNumeric: '968', symbol: '$'   , name: 'Surinamese dollar'                                         },
  {iso3: 'SSP', isoNumeric: '728', symbol: ''    , name: 'South Sudanese pound'                                      },
  {iso3: 'STD', isoNumeric: '678', symbol: ''    , name: 'São Tomé and Príncipe dobra'                               },
  {iso3: 'SVC', isoNumeric: '222', symbol: '$'   , name: 'Salvadoran colón'                                          },
  {iso3: 'SYP', isoNumeric: '760', symbol: '£'   , name: 'Syrian pound'                                              },
  {iso3: 'SZL', isoNumeric: '748', symbol: ''    , name: 'Swazi lilangeni'                                           },
  {iso3: 'THB', isoNumeric: '764', symbol: '฿'   , name: 'Thai baht'                                                 },
  {iso3: 'TJS', isoNumeric: '972', symbol: ''    , name: 'Tajikistani somoni'                                        },
  {iso3: 'TMT', isoNumeric: '934', symbol: ''    , name: 'Turkmenistani manat'                                       },
  {iso3: 'TND', isoNumeric: '788', symbol: ''    , name: 'Tunisian dinar'                                            },
  {iso3: 'TOP', isoNumeric: '776', symbol: ''    , name: 'Tongan paʻanga'                                            },
  {iso3: 'TRY', isoNumeric: '949', symbol: ''    , name: 'Turkish lira'                                              },
  {iso3: 'TTD', isoNumeric: '780', symbol: 'TT$' , name: 'Trinidad and Tobago dollar'                                },
  {iso3: 'TWD', isoNumeric: '901', symbol: 'NT$' , name: 'New Taiwan dollar'                                         },
  {iso3: 'TZS', isoNumeric: '834', symbol: ''    , name: 'Tanzanian shilling'                                        },
  {iso3: 'UAH', isoNumeric: '980', symbol: '₴'   , name: 'Ukrainian hryvnia'                                         },
  {iso3: 'UGX', isoNumeric: '800', symbol: ''    , name: 'Ugandan shilling'                                          },
  {iso3: 'USD', isoNumeric: '840', symbol: '$'   , name: 'United States dollar'                                      },
  {iso3: 'USN', isoNumeric: '997', symbol: ''    , name: 'United States dollar (next day) (funds code)'              },
  {iso3: 'UYI', isoNumeric: '940', symbol: ''    , name: 'Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)'},
  {iso3: 'UYU', isoNumeric: '858', symbol: '$U'  , name: 'Uruguayan peso'                                            },
  {iso3: 'UZS', isoNumeric: '860', symbol: 'лв'  , name: 'Uzbekistan som'                                            },
  {iso3: 'VEF', isoNumeric: '937', symbol: 'Bs'  , name: 'Venezuelan bolívar'                                        },
  {iso3: 'VND', isoNumeric: '704', symbol: '₫'   , name: 'Vietnamese đồng'                                           },
  {iso3: 'VUV', isoNumeric: '548', symbol: ''    , name: 'Vanuatu vatu'                                              },
  {iso3: 'WST', isoNumeric: '882', symbol: ''    , name: 'Samoan tala'                                               },
  {iso3: 'XAF', isoNumeric: '950', symbol: ''    , name: 'CFA franc BEAC'                                            },
  {iso3: 'XAG', isoNumeric: '961', symbol: ''    , name: 'Silver (one troy ounce)'                                   },
  {iso3: 'XAU', isoNumeric: '959', symbol: ''    , name: 'Gold (one troy ounce)'                                     },
  {iso3: 'XBA', isoNumeric: '955', symbol: ''    , name: 'European Composite Unit(EURCO) (bond market unit)'         },
  {iso3: 'XBB', isoNumeric: '956', symbol: ''    , name: 'European Monetary Unit(E.M.U.-6) (bond market unit)'       },
  {iso3: 'XBC', isoNumeric: '957', symbol: ''    , name: 'European Unit of Account 9(E.U.A.-9) (bond market unit)'   },
  {iso3: 'XBD', isoNumeric: '958', symbol: ''    , name: 'European Unit of Account 17(E.U.A.-17) (bond market unit)' },
  {iso3: 'XCD', isoNumeric: '951', symbol: '$'   , name: 'East Caribbean dollar'                                     },
  {iso3: 'XDR', isoNumeric: '960', symbol: ''    , name: 'Special drawing rights'                                    },
  {iso3: 'XOF', isoNumeric: '952', symbol: ''    , name: 'CFA franc BCEAO'                                           },
  {iso3: 'XPD', isoNumeric: '964', symbol: ''    , name: 'Palladium (one troy ounce)'                                },
  {iso3: 'XPF', isoNumeric: '953', symbol: ''    , name: 'CFP franc(franc Pacifique)'                                },
  {iso3: 'XPT', isoNumeric: '962', symbol: ''    , name: 'Platinum (one troy ounce)'                                 },
  {iso3: 'XSU', isoNumeric: '994', symbol: ''    , name: 'SUCRE'                                                     },
  {iso3: 'XTS', isoNumeric: '963', symbol: ''    , name: 'Code reserved for testing purposes'                        },
  {iso3: 'XUA', isoNumeric: '965', symbol: ''    , name: 'ADB Unit of Account'                                       },
  {iso3: 'XXX', isoNumeric: '999', symbol: ''    , name: 'No currency'                                               },
  {iso3: 'YER', isoNumeric: '886', symbol: '﷼'   , name: 'Yemeni rial'                                               },
  {iso3: 'ZAR', isoNumeric: '710', symbol: 'R'   , name: 'South African rand'                                        },
  {iso3: 'ZMW', isoNumeric: '967', symbol: ''    , name: 'Zambian kwacha'                                            },
  {iso3: 'ZWL', isoNumeric: '932', symbol: ''    , name: 'Zimbabwean dollar A/10'                                    }
]);


export const CURRENCIES_PER_COUNTRY_LIST = A([
  {currency: 'AED', country: 'AE'},
  {currency: 'AFN', country: 'AF'},
  {currency: 'ALL', country: 'AL'},
  {currency: 'AMD', country: 'AM'},
  {currency: 'ANG', country: 'CW'},
  {currency: 'ANG', country: 'SX'},
  {currency: 'AOA', country: 'AO'},
  {currency: 'ARS', country: 'AR'},
  {currency: 'AUD', country: 'AU'},
  {currency: 'AUD', country: 'CX'},
  {currency: 'AUD', country: 'CC'},
  {currency: 'AUD', country: 'HM'},
  {currency: 'AUD', country: 'KI'},
  {currency: 'AUD', country: 'NR'},
  {currency: 'AUD', country: 'NF'},
  {currency: 'AUD', country: 'TV'},
  {currency: 'AWG', country: 'AW'},
  {currency: 'AZN', country: 'AZ'},
  {currency: 'BAM', country: 'BA'},
  {currency: 'BBD', country: 'BB'},
  {currency: 'BDT', country: 'BD'},
  {currency: 'BGN', country: 'BG'},
  {currency: 'BHD', country: 'BH'},
  {currency: 'BIF', country: 'BI'},
  {currency: 'BMD', country: 'BM'},
  {currency: 'BND', country: 'BN'},
  {currency: 'BOB', country: 'BO'},
  {currency: 'BOV', country: 'BO'},
  {currency: 'BRL', country: 'BR'},
  {currency: 'BSD', country: 'BS'},
  {currency: 'BTN', country: 'BT'},
  {currency: 'BWP', country: 'BW'},
  {currency: 'BYN', country: 'BY'},
  {currency: 'BZD', country: 'BZ'},
  {currency: 'CAD', country: 'CA'},
  {currency: 'CDF', country: 'CD'},
  {currency: 'CHE', country: 'CH'},
  {currency: 'CHF', country: 'LI'},
  {currency: 'CHF', country: 'CH'},
  {currency: 'CHW', country: 'CH'},
  {currency: 'CLF', country: 'CL'},
  {currency: 'CLP', country: 'CL'},
  {currency: 'CNY', country: 'CN'},
  {currency: 'COP', country: 'CO'},
  {currency: 'COU', country: 'CO'},
  {currency: 'CRC', country: 'CR'},
  {currency: 'CUC', country: 'CU'},
  {currency: 'CUP', country: 'CU'},
  {currency: 'CVE', country: 'CV'},
  {currency: 'CZK', country: 'CZ'},
  {currency: 'DJF', country: 'DJ'},
  {currency: 'DKK', country: 'DK'},
  {currency: 'DKK', country: 'FO'},
  {currency: 'DKK', country: 'GL'},
  {currency: 'DOP', country: 'DO'},
  {currency: 'DZD', country: 'DZ'},
  {currency: 'EGP', country: 'EG'},
  {currency: 'ERN', country: 'ER'},
  {currency: 'ETB', country: 'ET'},
  {currency: 'EUR', country: 'AX'},
  {currency: 'EUR', country: 'AD'},
  {currency: 'EUR', country: 'AT'},
  {currency: 'EUR', country: 'BE'},
  {currency: 'EUR', country: 'CY'},
  {currency: 'EUR', country: 'EE'},
  {currency: 'EUR', country: 'FI'},
  {currency: 'EUR', country: 'FR'},
  {currency: 'EUR', country: 'GF'},
  {currency: 'EUR', country: 'TF'},
  {currency: 'EUR', country: 'DE'},
  {currency: 'EUR', country: 'GR'},
  {currency: 'EUR', country: 'GP'},
  {currency: 'EUR', country: 'VA'},
  {currency: 'EUR', country: 'IE'},
  {currency: 'EUR', country: 'IT'},
  {currency: 'EUR', country: 'LV'},
  {currency: 'EUR', country: 'LT'},
  {currency: 'EUR', country: 'LU'},
  {currency: 'EUR', country: 'MT'},
  {currency: 'EUR', country: 'MQ'},
  {currency: 'EUR', country: 'YT'},
  {currency: 'EUR', country: 'MC'},
  {currency: 'EUR', country: 'ME'},
  {currency: 'EUR', country: 'NL'},
  {currency: 'EUR', country: 'PT'},
  {currency: 'EUR', country: 'RE'},
  {currency: 'EUR', country: 'BL'},
  {currency: 'EUR', country: 'MF'},
  {currency: 'EUR', country: 'PM'},
  {currency: 'EUR', country: 'SM'},
  {currency: 'EUR', country: 'SK'},
  {currency: 'EUR', country: 'SI'},
  {currency: 'EUR', country: 'ES'},
  {currency: 'FJD', country: 'FJ'},
  {currency: 'FKP', country: 'FK'},
  {currency: 'GBP', country: 'GG'},
  {currency: 'GBP', country: 'IM'},
  {currency: 'GBP', country: 'JE'},
  {currency: 'GBP', country: 'GB'},
  {currency: 'GEL', country: 'GE'},
  {currency: 'GHS', country: 'GH'},
  {currency: 'GIP', country: 'GI'},
  {currency: 'GMD', country: 'GM'},
  {currency: 'GNF', country: 'GN'},
  {currency: 'GTQ', country: 'GT'},
  {currency: 'GYD', country: 'GY'},
  {currency: 'HKD', country: 'HK'},
  {currency: 'HNL', country: 'HN'},
  {currency: 'HRK', country: 'HR'},
  {currency: 'HTG', country: 'HT'},
  {currency: 'HUF', country: 'HU'},
  {currency: 'IDR', country: 'ID'},
  {currency: 'ILS', country: 'IL'},
  {currency: 'INR', country: 'BT'},
  {currency: 'INR', country: 'IN'},
  {currency: 'IQD', country: 'IQ'},
  {currency: 'IRR', country: 'IR'},
  {currency: 'ISK', country: 'IS'},
  {currency: 'JMD', country: 'JM'},
  {currency: 'JOD', country: 'JO'},
  {currency: 'JPY', country: 'JP'},
  {currency: 'KES', country: 'KE'},
  {currency: 'KGS', country: 'KG'},
  {currency: 'KHR', country: 'KH'},
  {currency: 'KMF', country: 'KM'},
  {currency: 'KPW', country: 'KP'},
  {currency: 'KRW', country: 'KR'},
  {currency: 'KWD', country: 'KW'},
  {currency: 'KYD', country: 'KY'},
  {currency: 'KZT', country: 'KZ'},
  {currency: 'LAK', country: 'LA'},
  {currency: 'LBP', country: 'LB'},
  {currency: 'LKR', country: 'LK'},
  {currency: 'LRD', country: 'LR'},
  {currency: 'LSL', country: 'LS'},
  {currency: 'LYD', country: 'LY'},
  {currency: 'MAD', country: 'MA'},
  {currency: 'MAD', country: 'EH'},
  {currency: 'MDL', country: 'MD'},
  {currency: 'MGA', country: 'MG'},
  {currency: 'MKD', country: 'MK'},
  {currency: 'MMK', country: 'MM'},
  {currency: 'MNT', country: 'MN'},
  {currency: 'MOP', country: 'MO'},
  {currency: 'MRO', country: 'MR'},
  {currency: 'MUR', country: 'MU'},
  {currency: 'MVR', country: 'MV'},
  {currency: 'MWK', country: 'MW'},
  {currency: 'MXN', country: 'MX'},
  {currency: 'MXV', country: 'MX'},
  {currency: 'MYR', country: 'MY'},
  {currency: 'MZN', country: 'MZ'},
  {currency: 'NAD', country: 'NA'},
  {currency: 'NGN', country: 'NG'},
  {currency: 'NIO', country: 'NI'},
  {currency: 'NOK', country: 'BV'},
  {currency: 'NOK', country: 'NO'},
  {currency: 'NOK', country: 'SJ'},
  {currency: 'NPR', country: 'NP'},
  {currency: 'NZD', country: 'CK'},
  {currency: 'NZD', country: 'NZ'},
  {currency: 'NZD', country: 'NU'},
  {currency: 'NZD', country: 'PN'},
  {currency: 'NZD', country: 'TK'},
  {currency: 'OMR', country: 'OM'},
  {currency: 'PAB', country: 'PA'},
  {currency: 'PEN', country: 'PE'},
  {currency: 'PGK', country: 'PG'},
  {currency: 'PHP', country: 'PH'},
  {currency: 'PKR', country: 'PK'},
  {currency: 'PLN', country: 'PL'},
  {currency: 'PYG', country: 'PY'},
  {currency: 'QAR', country: 'QA'},
  {currency: 'RON', country: 'RO'},
  {currency: 'RSD', country: 'RS'},
  {currency: 'RUB', country: 'RU'},
  {currency: 'RWF', country: 'RW'},
  {currency: 'SAR', country: 'SA'},
  {currency: 'SBD', country: 'SB'},
  {currency: 'SCR', country: 'SC'},
  {currency: 'SDG', country: 'SD'},
  {currency: 'SEK', country: 'SE'},
  {currency: 'SGD', country: 'SG'},
  {currency: 'SHP', country: 'SH'},
  {currency: 'SLL', country: 'SL'},
  {currency: 'SOS', country: 'SO'},
  {currency: 'SRD', country: 'SR'},
  {currency: 'SSP', country: 'SS'},
  {currency: 'STD', country: 'ST'},
  {currency: 'SVC', country: 'SV'},
  {currency: 'SYP', country: 'SY'},
  {currency: 'SZL', country: 'SZ'},
  {currency: 'THB', country: 'TH'},
  {currency: 'TJS', country: 'TJ'},
  {currency: 'TMT', country: 'TM'},
  {currency: 'TND', country: 'TN'},
  {currency: 'TOP', country: 'TO'},
  {currency: 'TRY', country: 'TR'},
  {currency: 'TTD', country: 'TT'},
  {currency: 'TWD', country: 'TW'},
  {currency: 'TZS', country: 'TZ'},
  {currency: 'UAH', country: 'UA'},
  {currency: 'UGX', country: 'UG'},
  {currency: 'USD', country: 'AS'},
  {currency: 'USD', country: 'BQ'},
  {currency: 'USD', country: 'IO'},
  {currency: 'USD', country: 'EC'},
  {currency: 'USD', country: 'SV'},
  {currency: 'USD', country: 'GU'},
  {currency: 'USD', country: 'HT'},
  {currency: 'USD', country: 'MH'},
  {currency: 'USD', country: 'FM'},
  {currency: 'USD', country: 'MP'},
  {currency: 'USD', country: 'PW'},
  {currency: 'USD', country: 'PA'},
  {currency: 'USD', country: 'PR'},
  {currency: 'USD', country: 'TL'},
  {currency: 'USD', country: 'TC'},
  {currency: 'USD', country: 'UM'},
  {currency: 'USD', country: 'US'},
  {currency: 'USD', country: 'VG'},
  {currency: 'USD', country: 'VI'},
  {currency: 'USN', country: 'US'},
  {currency: 'UYI', country: 'UY'},
  {currency: 'UYU', country: 'UY'},
  {currency: 'UZS', country: 'UZ'},
  {currency: 'VEF', country: 'VE'},
  {currency: 'VND', country: 'VN'},
  {currency: 'VUV', country: 'VU'},
  {currency: 'WST', country: 'WS'},
  {currency: 'XAF', country: 'CM'},
  {currency: 'XAF', country: 'CF'},
  {currency: 'XAF', country: 'TD'},
  {currency: 'XAF', country: 'CG'},
  {currency: 'XAF', country: 'GQ'},
  {currency: 'XAF', country: 'GA'},
  {currency: 'XCD', country: 'AI'},
  {currency: 'XCD', country: 'AG'},
  {currency: 'XCD', country: 'DM'},
  {currency: 'XCD', country: 'GD'},
  {currency: 'XCD', country: 'MS'},
  {currency: 'XCD', country: 'KN'},
  {currency: 'XCD', country: 'LC'},
  {currency: 'XCD', country: 'VC'},
  {currency: 'XOF', country: 'BJ'},
  {currency: 'XOF', country: 'BF'},
  {currency: 'XOF', country: 'CI'},
  {currency: 'XOF', country: 'GW'},
  {currency: 'XOF', country: 'ML'},
  {currency: 'XOF', country: 'NE'},
  {currency: 'XOF', country: 'SN'},
  {currency: 'XOF', country: 'TG'},
  {currency: 'XPF', country: 'PF'},
  {currency: 'XPF', country: 'NC'},
  {currency: 'XPF', country: 'WF'},
  {currency: 'YER', country: 'YE'},
  {currency: 'ZAR', country: 'LS'},
  {currency: 'ZAR', country: 'NA'},
  {currency: 'ZAR', country: 'ZA'},
  {currency: 'ZMW', country: 'ZM'},
  {currency: 'ZWL', country: 'ZW'}
]);


export default {
  CURRENCIES_LIST,
  CURRENCIES_PER_COUNTRY_LIST
};
